update mac80211

diff --git a/package/kernel/mac80211/files/qca-nss-pbuf.init b/package/kernel/mac80211/files/qca-nss-pbuf.init
--- a/package/kernel/mac80211/files/qca-nss-pbuf.init
+++ b/package/kernel/mac80211/files/qca-nss-pbuf.init
@@ -14,14 +14,20 @@
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
 
-START=95
+START=27
 NAME=qca-nss-pbuf
+pbuf_config_applied=0
 
 reload_wifi() {
-  if [ -r /sys/module/ath11k/parameters/nss_offload ]; then
-    nss_offload=$(cat /sys/module/ath11k/parameters/nss_offload 2> /dev/null)
-    [ "$nss_offload" -eq 1 ] && wifi up
-  fi
+  local do_reload nss_offload
+
+  config_load pbuf
+  config_get_bool do_reload opt reload_wifi 0
+  [ "$do_reload" -eq 1 ] || return 0
+
+  [ -r /sys/module/ath11k/parameters/nss_offload ] || return 0
+  nss_offload=$(cat /sys/module/ath11k/parameters/nss_offload 2> /dev/null)
+  [ "${nss_offload:-0}" -eq 1 ] && wifi up
 }
 
 get_num_cpus() {
@@ -31,46 +37,54 @@ get_num_cpus() {
 }
 
 apply_sysctl() {
-  [ "$(sysctl -n -e dev.nss.general.redirect)" -eq 0 ] && /etc/init.d/qca-nss-ecm start
+  local nss_redirect extra_pbuf
+
+  nss_redirect=$(sysctl -n -e dev.nss.general.redirect 2> /dev/null)
+  if [ -n "$nss_redirect" ] && [ "$nss_redirect" -eq 0 ] && [ -x /etc/init.d/qca-nss-ecm ]; then
+    /etc/init.d/qca-nss-ecm start
+  fi
 
   # Running this script multiple times is useless, as extra_pbuf_core0
   # can't be changed if it is allocated, assume it's already been run.
-  if [ "$(sysctl -n -e dev.nss.n2hcfg.extra_pbuf_core0)" -eq 0 ]; then
-    logger -t $NAME "$board - setting dev.nss.n2hcfg.extra_pbuf_core0=$extra_pbuf_core0"
+  extra_pbuf=$(sysctl -n -e dev.nss.n2hcfg.extra_pbuf_core0 2> /dev/null)
+  if [ "${extra_pbuf:-0}" -eq 0 ]; then
+    logger -t "$NAME" "$board - setting dev.nss.n2hcfg.extra_pbuf_core0=$extra_pbuf_core0"
     sysctl -w dev.nss.n2hcfg.extra_pbuf_core0="$extra_pbuf_core0" > /dev/null 2>&1
   else
-    logger -t $NAME "Sysctl key 'extra_pbuf_core0' already set to '""$extra_pbuf_core0""'. Skipping applying wifi nss configs"
+    logger -t "$NAME" "Sysctl key 'extra_pbuf_core0' already set to '""$extra_pbuf_core0""'. Skipping applying wifi nss configs"
   fi
 
-  sysctl -w dev.nss.n2hcfg.n2h_high_water_core0="$n2h_high_water_core0" > /dev/null 2>&1
-
-  logger -t $NAME "$board - setting dev.nss.n2hcfg.n2h_wifi_pool_buf=$n2h_wifi_pool_buf"
+  logger -t "$NAME" "$board - setting dev.nss.n2hcfg.n2h_wifi_pool_buf=$n2h_wifi_pool_buf"
   sysctl -w dev.nss.n2hcfg.n2h_wifi_pool_buf="$n2h_wifi_pool_buf" > /dev/null 2>&1
 
-  logger -t $NAME "$board - setting dev.nss.n2hcfg.n2h_high_water_core0=$n2h_high_water_core0"
+  logger -t "$NAME" "$board - setting dev.nss.n2hcfg.n2h_high_water_core0=$n2h_high_water_core0"
   sysctl -w dev.nss.n2hcfg.n2h_high_water_core0="$n2h_high_water_core0" > /dev/null 2>&1
 
 }
 
 apply_nss_config() {
-  local auto_scale n2h_queue_limit_core0 n2h_queue_limit_core1 num_cpus
-  local hash_bitmap
+  local auto_scale n2h_queue_limit_core0 n2h_queue_limit_core1
 
   if [ ! -r /sys/module/ath11k/parameters/nss_offload ]; then
-    logger -t $NAME "Module parameter '/sys/module/ath11k/parameters/nss_offload' does NOT exist. Skipping applying wifi nss configs"
-    exit 1
+    [ -d /sys/module/ath11k ] && logger -t "$NAME" -p user.notice "Module parameter '/sys/module/ath11k/parameters/nss_offload' does NOT exist. Skipping applying wifi nss configs"
+    return 0
   fi
 
   enable_nss_offload=$(cat /sys/module/ath11k/parameters/nss_offload)
 
   if [ "$enable_nss_offload" -ne "1" ]; then
-    logger -t $NAME -s user.warn "Module parameter 'nss_offload=0'. Skipping applying wifi nss configs"
-    exit 1
+    logger -t "$NAME" -p user.notice "Module parameter 'nss_offload=0'. Skipping applying wifi nss configs"
+    return 0
   fi
 
   [ ! -d "/proc/sys/dev/nss/rps" ] && {
-    logger -s -t $NAME -p user.error "NSS driver not loaded or disabled! Exiting... "
-    exit 1
+    logger -t "$NAME" -p user.notice "NSS RPS sysctls are unavailable. Skipping applying wifi nss configs"
+    return 0
+  }
+
+  [ ! -d "/proc/sys/dev/nss/n2hcfg" ] && {
+    logger -t "$NAME" -p user.notice "NSS n2hcfg sysctls are unavailable. Skipping applying wifi nss configs"
+    return 0
   }
 
   config_load pbuf
@@ -89,26 +103,26 @@ apply_nss_config() {
   if memory_profile=$(uci_get pbuf.opt.memory_profile); then
     case "$memory_profile" in
       1024 | 1g* | 512 | 512m* | 256 | 256m*)
-        logger -t $NAME "Using custom memory profile - $board"
+        logger -t "$NAME" "Using custom memory profile - $board"
         ;;
       off* | false* | disable* | 0)
-        logger -s -t $NAME -p user.warn "NSS pbuf option 'memory_profile=off'. Not running. Enable if you have issues connecting more than 65 clients"
-        exit 0
+        logger -t "$NAME" -p user.warn "NSS pbuf option 'memory_profile=off'. Not running. Enable if you have issues connecting more than 65 clients"
+        return 0
         ;;
       auto)
         memtotal=$(awk '/MemTotal/{print $2}' /proc/meminfo)
         [ "$memtotal" -gt 512000 ] && memory_profile=1024
         [ "$memtotal" -le 512000 ] && memory_profile=512
         [ "$memtotal" -le 256000 ] && memory_profile=256
-        logger -t $NAME "Setting n2hcfg values for board: $board"
+        logger -t "$NAME" "Setting n2hcfg values for board: $board"
         ;;
       *)
-        logger -s -t $NAME -p user.error "Unknown profile $memory_profile. Choose auto, 1gb, 512mb, or 256mb"
-        exit 1
+        logger -t "$NAME" -p user.error "Unknown profile $memory_profile. Choose auto, 1gb, 512mb, or 256mb"
+        return 1
         ;;
     esac
   else
-    exit 0
+    return 0
   fi
 
   case "$memory_profile" in
@@ -125,6 +139,8 @@ apply_nss_config() {
       extra_pbuf_core0=3100000 n2h_high_water_core0=30258 n2h_wifi_pool_buf=4096 apply_sysctl
       ;;
   esac
+
+  pbuf_config_applied=1
 }
 
 set_stats_disable() {
@@ -132,51 +148,58 @@ set_stats_disable() {
   local stats_disable
   config_load pbuf
   config_get stats_disable opt stats_disable 1
+  [ -d /sys/kernel/debug/ath11k ] || return 0
 
   find /sys/kernel/debug/ath11k -name stats_disable | while read -r stats_file; do
     stats_msg_prefix="Disabling"
     [ "$stats_disable" -eq 0 ] && stats_msg_prefix="Enabling"
-    logger -t $NAME -p user.notice "$stats_msg_prefix ath11k stats"
+    logger -t "$NAME" -p user.notice "$stats_msg_prefix ath11k stats"
     echo "$stats_disable" > "$stats_file"
   done
 }
 
 set_scaling_governor() {
 
-  local scaling_governor num_cpus
+  local scaling_governor num_cpus governor_file
   config_load pbuf
   config_get scaling_governor opt scaling_governor
 
   scaling_available_governors=/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
 
   if [ -r "$scaling_available_governors" ]; then
-    scaling_available_governors=$(cat $scaling_available_governors)
+    scaling_available_governors=$(cat "$scaling_available_governors")
   else
     return 0
   fi
 
   if [ -n "$scaling_available_governors" ] && [ -n "$scaling_governor" ]; then
-    if [[ "$scaling_available_governors" =~ $scaling_governor ]]; then
-      logger -t $NAME -p user.notice "Setting CPU scaling governor to '$scaling_governor'"
+    case " $scaling_available_governors " in
+    *" $scaling_governor "*)
+      logger -t "$NAME" -p user.notice "Setting CPU scaling governor to '$scaling_governor'"
       num_cpus=$(get_num_cpus)
       for num in $(seq 0 $((num_cpus - 1))); do
-        echo "$scaling_governor" > "/sys/devices/system/cpu/cpu${num}/cpufreq/scaling_governor"
+        governor_file="/sys/devices/system/cpu/cpu${num}/cpufreq/scaling_governor"
+        [ -w "$governor_file" ] && echo "$scaling_governor" > "$governor_file"
       done
-    else
-      logger -t $NAME -p user.error "'$scaling_governor' not available in CPU governors [ $scaling_available_governors ]"
-    fi
+      ;;
+    *)
+      logger -t "$NAME" -p user.error "'$scaling_governor' not available in CPU governors [ $scaling_available_governors ]"
+      ;;
+    esac
   fi
 }
 
 start() {
 
+  pbuf_config_applied=0
   set_scaling_governor
   set_stats_disable
-  apply_nss_config
+  apply_nss_config || return 1
+  [ "$pbuf_config_applied" -eq 1 ] || return 0
 
   num_cpus=$(get_num_cpus)
   hash_bitmap="$(((1 << num_cpus) - 1))"
-  sysctl -w dev.nss.rps.hash_bitmap=$hash_bitmap > /dev/null 2>&1
+  [ -w /proc/sys/dev/nss/rps/hash_bitmap ] && sysctl -w dev.nss.rps.hash_bitmap="$hash_bitmap" > /dev/null 2>&1
   reload_wifi
 
 }
